### ISSUE TITLE
Inside your Seq2Seq (Transformers), Observe the parameter forward_expansion.

### ISSUE THREAD

**Issue by KrishPro** [aladdinpersson/Machine-Learning-Collection#100]
You've defined forward_expansion as 4,

See the [implementation](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/transformer.py#L304,L306) of the FeedForward network at the end of encoders & decoders

So, putting your variable in code. will look like -
```python
self.linear1 = Linear(d_model,  4, **factory_kwargs)
self.dropout = Dropout(dropout)
self.linear2 = Linear(4, d_model, **factory_kwargs)
```
where `d_model` = 512 (`emb_size`)

Obserser PyTorch's official [implementation](https://pytorch.org/tutorials/beginner/translation_transformer.html#seq2seq-network-using-transformer) for more clearance.

I will suggest you to change that variable to something bigger like `512`, `1024` or `2048`
I am surprised that even after using `4` as `dim_feedforward` (Or what you call it `forward_expansion`), You're getting great results

**Comment by KrishPro** [comment]
Looking forward for you're comments on this issue @aladdinpersson

**Comment by KrishPro** [comment]
The pinned comment on the video [Pytorch Transformers for Machine Translation](https://www.youtube.com/watch?v=M6adRGJe5cQ) has already stated this issue.

> One mistake I made in the video was when writing:
forward_expansion = 4
>I thought this would be the number of nodes to be expanded (similar to how the original paper did) but it's actually the number of nodes. Which means that going through the linear layer we are mapping to only 4 nodes in total, which obviously doesn't work. I think we're saved by the skip connections here so we still get decent performance but remember to change this!

I am closing this issue (considering this issue as a duplicate issue)

**Comment by aladdinpersson** [comment]
Yeah this was a big miss on my part, it seems pytorch has now changed the name for the variable because to name it forward expansion was imo very confusing. It's been fixed now. Need to re-run the training to see how much better it actually was than Seq2Seq with LSTMs
