### ISSUE TITLE
To learn positional encoding

### ISSUE THREAD

**Issue by gravitychen** [aladdinpersson/Machine-Learning-Collection#11]
Hi,nice work!
I have a question about transformer~

I wonder  how to change the nn.embedding(including inputs and positional encoding.) using learning method?

thanks!

**Comment by aladdinpersson** [comment]
Sorry for the late response. I haven't looked at how to use positional encoding so I can't help you with that unfortunately. Maybe [this](https://kazemnejad.com/blog/transformer_architecture_positional_encoding/) blogpost I found could help you.
