### ISSUE TITLE
How can I obtain the output of an intermediate layer (feature extraction) in Model Subclassing ?

### ISSUE THREAD

**Issue by Rajatsharma07** [aladdinpersson/Machine-Learning-Collection#13]
Please refer to the below link for more details on the issue.

https://stackoverflow.com/questions/64471742/skip-some-layers-in-keras-model-during-evaluation-validation-phase

My requirement is to override the Evaluation/Validation step after each epoch, with using the Existing Fit function.

Following below link does not work (when this code is written in test_step method)
https://keras.io/getting_started/faq/#how-can-i-obtain-the-output-of-an-intermediate-layer-feature-extraction

**Comment by aladdinpersson** [comment]
Seems you solved it from the stackoverflow comment: 

"Created a custom callback - on_epoch_end() method and passed the validation data and noted the evaluation. – Rajat Sharma Dec"

But yeah, I personally think I'd just use custom loops for that sort of thing
