### ISSUE TITLE
Error while using GPU

### ISSUE THREAD

**Issue by blgnksy** [aladdinpersson/Machine-Learning-Collection#14]
I have CUDA enabled GPU and using the exact same code in your [transformer from scratch code](https://github.com/aladdinpersson/Machine-Learning-Collection/commit/9f3b2a82c0b8b6ba8c16293d8118d8d8c888f8e6) I got the same error in #9 . The error is in line 66. When I inspect the your code, I couldn't figure out the problem.

**Comment by blgnksy** [comment]
I found the error and opened a PR #15

**Comment by aladdinpersson** [comment]
Yeah looks good
