### ISSUE TITLE
true_boxes list

### ISSUE THREAD

**Issue by Ekta246** [aladdinpersson/Machine-Learning-Collection#20]
The ML/Pytorch/object detection/metrics/mean_avg_precision.py is all what I was wanting for so long.
Great thanks to you @aladdinpersson 

But I just wanted to ask if how can I get the true_boxes list while integrating the code into my validation pipeline.
However, I can produce the pred_boxes list in my validation code since I know where I produce the detections, scores, classes etc.

Does it means I should take it same as pred_boxes list except for where the class_prediction is 0 according to the definition?
Am I right?

Thanks in advance

**Comment by aladdinpersson** [comment]
Sorry for late response. I'm not sure I completely understand the question, assuming you're asking about inference for yolo. So for inference you have the probability that there is an object in that particular cell then you would probably remove those that are under a certain prob_threshold then for the class prediction for the remaining preds you would just take the argmax
