### ISSUE TITLE
Getting error while executing Sementic segmentation w. UNET in pytorch

### ISSUE THREAD

**Issue by sautami26** [aladdinpersson/Machine-Learning-Collection#28]
Hi,
I watched your recent tutorial on sementic segmentation with pytorch. Being new to pytorch I was looking for some tutorial with good explanations especially in segmentation module and your tutorial came as a great help.
I tried to implement your way on a UNet network for segmentation on google-colab but getting an error. I tried to fix it but no luck. Can you please help me in fixing the error.
The error I am getting is:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-44-52ecac8110b5> in <module>()
     85 
     86 if __name__ == "__main__":
---> 87   main()

7 frames
<ipython-input-44-52ecac8110b5> in main()
     67 
     68   for epoch in range(Num_epochs):
---> 69     train_fn(train_loader, model, optimizer, loss_fn, scaler)
     70 
     71 

<ipython-input-44-52ecac8110b5> in train_fn(loader, model, optimizer, loss_fn, scaler)
      2   loop = tqdm(loader)
      3 
----> 4   for batch_idx, (data, targets) in enumerate(loop):
      5     data= data.to(device=device)
      6     targets= targets.float().unsqueeze(1).to(device=device)

/usr/local/lib/python3.6/dist-packages/tqdm/std.py in __iter__(self)
   1102                 fp_write=getattr(self.fp, 'write', sys.stderr.write))
   1103 
-> 1104         for obj in iterable:
   1105             yield obj
   1106             # Update and possibly print the progressbar.

/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py in __next__(self)
    433         if self._sampler_iter is None:
    434             self._reset()
--> 435         data = self._next_data()
    436         self._num_yielded += 1
    437         if self._dataset_kind == _DatasetKind.Iterable and \

/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py in _next_data(self)
    473     def _next_data(self):
    474         index = self._next_index()  # may raise StopIteration
--> 475         data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    476         if self._pin_memory:
    477             data = _utils.pin_memory.pin_memory(data)

/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py in fetch(self, possibly_batched_index)
     42     def fetch(self, possibly_batched_index):
     43         if self.auto_collation:
---> 44             data = [self.dataset[idx] for idx in possibly_batched_index]
     45         else:
     46             data = self.dataset[possibly_batched_index]

/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py in <listcomp>(.0)
     42     def fetch(self, possibly_batched_index):
     43         if self.auto_collation:
---> 44             data = [self.dataset[idx] for idx in possibly_batched_index]
     45         else:
     46             data = self.dataset[possibly_batched_index]

<ipython-input-37-340818cd6801> in __getitem__(self, index)
     17 
     18      if self.transform is not None:
---> 19        augmentations= self.transform(image=image, mask=mask)
     20        image = augmentations["image"]
     21        mask = augmentations["mask"]

TypeError: 'int' object is not callable

**Comment by aladdinpersson** [comment]
Seems to be an issue related to running it on Colab. Perhaps there is something wrong with the dataloading process in colab since that's where it looks to get the error, make you sure image and mask are correct in your __getitem__.

**Comment by sautami26** [comment]
Hi,
Thank you very much for your prompt response.
My dataset folder is set in the same pattern as mentioned in the tutorial
but the error still exists.

Regards
Sautami

**Comment by aladdinpersson** [comment]
I don't use colab and I think this error is associated with that. Will close this issue but if you find an issue with the code then just reopen
