### ISSUE TITLE
ProGan RuntimeError

### ISSUE THREAD

**Issue by extremety1989** [aladdinpersson/Machine-Learning-Collection#34]
i downloaded celeba_hq image dataset,modified config.py (DATASET = 'celeba_hq') , modified train.py( at main()    
     # import sys
    # sys.exit()) 
then when i run python train.py i got this error

`` return F.conv_transpose2d(
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [512, 512, 4, 4], but got 2-dimensional input of size [256, 512] instead``

**Comment by aladdinpersson** [comment]
Yeah sorry, I didn't push the latest version that I was working with. It should work now

**Comment by extremety1989** [comment]
thanks !

**Comment by extremety1989** [comment]
@aladdinpersson now i got RuntimeError: CUDA out of memory.   i have Intel core i7 NvidiaGeoforce 940 mx CUDA 11.1

**Comment by aladdinpersson** [comment]
Change the image size in config file from 128 to something lower like 4/8/16

**Comment by extremety1989** [comment]
@aladdinpersson that's strange even with image size 4 it does output same error. Maybe a bug in (Pytorch pip windows 10 version)  ?

**Comment by aladdinpersson** [comment]
From my understanding your gpu only has 2gb of vram which is probably the reason. You can try to reduce the number of channels in the config file and see if that works. Since we're creating all the conv layers etc for up to 1024x1024 generation you do need to have some vram because the parameters will be on the GPU. I haven't done any extensive tests but it runs on my GTX 1060 with 6gb vram

**Comment by extremety1989** [comment]
4gb of vram ,but it is okey, i will go on colab . Thanks!

**Comment by extremety1989** [comment]
@aladdinpersson sorry for bothering but in my colab i get this error:

``RuntimeError: Given transposed=1, weight of size [100, 256, 4, 4], expected input[8, 256, 1, 1] to have 100 channels, but got 256 channels instead``

**Comment by extremety1989** [comment]
well i fixed it with Z_DIM = 256
