### ISSUE TITLE
ProGAN Pretrained weights link is broken!

### ISSUE THREAD

**Issue by extremety1989** [aladdinpersson/Machine-Learning-Collection#35]
When i click to dowload pretrained weights i get redirected to https://github.com/aladdinpersson/Machine-Learning-Collection/tree/master/ML/Pytorch/GANs/ProGAN

**Comment by aladdinpersson** [comment]
I'll fix the link but it's also in the official release of the repository:
https://github.com/aladdinpersson/Machine-Learning-Collection/releases/tag/1.0

**Comment by extremety1989** [comment]
@aladdinpersson Great!

**Comment by extremety1989** [comment]
@aladdinpersson celeba_wgan_gp.pth.tar is missing

**Comment by aladdinpersson** [comment]
Where did you get celeba_wgan_gp.pth.tar from?

**Comment by extremety1989** [comment]
@aladdinpersson train.py at main()     
load_checkpoint(torch.load("celeba_wgan_gp.pth.tar"), gen, critic)
    gen.train()
    critic.train()

**Comment by aladdinpersson** [comment]
You might still be using the training file before I pushed the latest version, this is how it should look:

```python
if config.LOAD_MODEL:
        load_checkpoint(
            config.CHECKPOINT_GEN, gen, opt_gen, config.LEARNING_RATE,
        )
        load_checkpoint(
            config.CHECKPOINT_CRITIC, critic, opt_critic, config.LEARNING_RATE,
        )

gen.train()
critic.train()
```

**Comment by aladdinpersson** [comment]
Sorry for the confusion of the different versions. I accidently pushed an old version when I was trying trying to implement it & when I hadn't cleaned up parts of the code.

**Comment by extremety1989** [comment]
@aladdinpersson no pr, btw when i load pretrained model
SAVE_MODEL = False
LOAD_MODEL = True
do i need to train ? 

    gen.train()
    critic.train()
or i just 

import sys
system.exit() 
?

**Comment by aladdinpersson** [comment]
If you use the `generate_examples` [function ](https://github.com/aladdinpersson/Machine-Learning-Collection/blob/2a9c539b40da815f04be738bff8711c6b38bcbad/ML/Pytorch/GANs/ProGAN/utils.py#L78-L90) in the utils file it's going to automatically toggle `eval()` mode for the generator. What's important is just that you actually load the weights which you do by setting `LOAD_MODEL = True` as you mention. I don't follow what you mean with `system.exit()`.

**Comment by extremety1989** [comment]
do i need to put system.exit() to exit the training ?
``def main():
    # initialize gen and disc, note: discriminator should be called critic,
    # according to WGAN paper (since it no longer outputs between [0, 1])
    # but really who cares..
    gen = Generator(
        config.Z_DIM, config.IN_CHANNELS, img_channels=config.CHANNELS_IMG
    ).to(config.DEVICE)
    critic = Discriminator(
        config.Z_DIM, config.IN_CHANNELS, img_channels=config.CHANNELS_IMG
    ).to(config.DEVICE)

    # initialize optimizers and scalers for FP16 training
    opt_gen = optim.Adam(gen.parameters(), lr=config.LEARNING_RATE, betas=(0.0, 0.99))
    opt_critic = optim.Adam(
        critic.parameters(), lr=config.LEARNING_RATE, betas=(0.0, 0.99)
    )
    scaler_critic = torch.cuda.amp.GradScaler()
    scaler_gen = torch.cuda.amp.GradScaler()

    # for tensorboard plotting
    writer = SummaryWriter(f"logs/gan1")

    if config.LOAD_MODEL:
        load_checkpoint(
            config.CHECKPOINT_GEN, gen, opt_gen, config.LEARNING_RATE,
        )
        load_checkpoint(
            config.CHECKPOINT_CRITIC, critic, opt_critic, config.LEARNING_RATE,
        )
    import sys
    sys.exit()
    gen.train()
    critic.train()
``

**Comment by extremety1989** [comment]
@aladdinpersson well i released that generate_examples() in main.py is not used, is it normal ?
