### ISSUE TITLE
Train set up Yolov3

### ISSUE THREAD

**Issue by salokin1997** [aladdinpersson/Machine-Learning-Collection#39]
Hey Aladdin,
Thank you for your great tutorial! I have a question about your Yolov3 training. I've tried training Yolo on Pascal VOC with my own  settings, but I'm stuck at a mAP of 57.5. How did you get 78.2 mAP? Can you tell me your settings?

My settings:
```
BATCH_SIZE = 16
IMAGE_SIZE = 416
LEARNING_RATE = 1e-5
WEIGHT_DECAY = 1e-4
NUM_EPOCHS = 500
CONF_THRESHOLD = 0.2
MAP_IOU_THRESH = 0.5
NMS_IOU_THRESH = 0.45
```

**Comment by johnnylord** [comment]
I have used FOCAL loss for objectness confidence and CIoU loss for bounding box regression. But I only got 71 mAP@0.5. I still trying to make it to 78.2.

@aladdinpersson Hope you can point some ways to improve it. BTW, thanks for your great work.

**Comment by salokin1997** [comment]
@johnnylord  Thank you for your good advice. I looked at your repository and tried to implement the loss. However, I am relatively new to DL and cannot reproduce your good results. How many epochs have you trained your network? And do you have any hints for me to get better results?

**Comment by johnnylord** [comment]
I have modified the code from @aladdinpersson and release two models trained on PASCAL VOC and MS COCO dataset. 
Here's the project repo https://github.com/johnnylord/trytry-detection. Hope it can help you @salokin1997 .

Here's the training result:
![image](https://user-images.githubusercontent.com/17330084/120736697-4d82ae00-c51f-11eb-8b04-83c3cdfd128d.png)
