### ISSUE TITLE
Why do you need to slice captions? 

### ISSUE THREAD

**Issue by concrete13377** [aladdinpersson/Machine-Learning-Collection#7]
https://github.com/AladdinPerzon/Machine-Learning-Collection/blob/9f3b2a82c0b8b6ba8c16293d8118d8d8c888f8e6/ML/Pytorch/more_advanced/image_captioning/train.py#L82

Hello, thank you for your version of the image captioning solution!
However, one thing is not clear to me. Why would you do that slice? If I correctly understood the captions, in that case, is a padded batch of captions, so it looks like:
1 1 1 1 1 2
1 1 1 2 0 0
1 1 1 1 2 0

and if you make a slice [:,: - 1]
that would be:
1 1 1 1 1
1 1 1 2 0
1 1 1 1 2
(1 is any token, 2 is <EOS> and 0 is padding)

So if you want to get rid of <EOS> tokens that would not work.

**Comment by AladdinPerzon** [comment]
The model is always working on predicting the next time step, so when we're sending in the captions to the model not including the last one. So we send in all expect the last one (since this will be the last one predicted) and in the cost function we send in the entire caption length.

**Comment by aladdinpersson** [comment]
Closing, let me know if you still have any questions about this!
