### ISSUE TITLE
YOLOv3, problems in get_evaluation_bboxes

### ISSUE THREAD

**Issue by SimoDB90** [aladdinpersson/Machine-Learning-Collection#74]
Hi there! First, thanks for your works! 
I would like to know if it's a issue or i am the only one with such a problem.
I'm trying to run the train on 8 examples, with batch size of 4 (but even on training loader is the same):
when i change the CONF_THRESHOLD to less than 0.6, the train seems to never go ahead on "mean average precision": the print(mapval.item) never appear.
When i change to (or equal than) 0.6, it is computed but the MAP is always 0, the no obj accuracy is always 100% and obj accuracy is always 0%.

I ran the train on training loader for 70 epochs more or less, with CONF_THRESHOLD at 0.6, but MAP was something like 0.004. I printed some images but i had several dozen of boxes in the image.

i tried to debug it but without any luck. Can someone elaborate it?

**Comment by mmuneeburahman** [comment]
How did you solve this issue?
