### ISSUE TITLE
error when running code

### ISSUE THREAD

**Issue by javismiles** [aladdinpersson/Machine-Learning-Collection#9]
when running your code i get this error:

RuntimeError: Expected object of device type cuda but got device type cpu for argument #3 'index' in call to _th_index_select

any tips? thank you

**Comment by AladdinPerzon** [comment]
Do you have CUDA enabled GPU? The default argument for running the Transformer from scratch code is cuda. If you want to run it on CPU you need to change this call. Specifically change the call of

```python
model = Transformer(src_vocab_size, trg_vocab_size, src_pad_idx, trg_pad_idx).to(
        device
)
```

to

```
model = Transformer(src_vocab_size, trg_vocab_size, src_pad_idx, trg_pad_idx, device='cpu').to(
        device
)
```

**Comment by aladdinpersson** [comment]
I'm closing this, let me know if you still wonder about this!

**Comment by javismiles** [comment]
thank you very much, I couldn´t test it yet but thank you for the suggestion to fix the issue, will try it as soon as I can, best wishes

**Comment by blgnksy** [comment]
I have CUDA enabled GPU and using the exact same code. I got the same error as @javismiles had gotten. The error is in line 66. When I inspect the your code, I couldn't figure out the problem.
